name: Build documentation and deploy it to the website
on:
  push:
    branches: main
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/deploy-ss3-docs.yml@add_ss3_docs