name: Build documentation and deploy it to the website
on:
  push:
    branches: main
    paths:
      - '**.tex'
      - '**.Rmd'
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/deploy-ss3-docs.yml@main