name: Build pdf using texlive
on:
  workflow_dispatch:
  push:
    paths:
      - '**.tex'
  pull_request:
    paths:
      - '**.tex'
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/build-ss3-manual-pdf.yml@main
