name: Build pdf for last release using texlive
on: [workflow_dispatch]
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/build-ss3-manual-pdf.yml@main
    with:
    # Note: upon new releases, will need to update this ref
      ref: 'v3.30.18'