name: Build documentation and deploy it to the website
on:
  push:
    branches: main
    paths:
      - '**.tex'
      - '**.Rmd'
      - 'docs/**'
      - 'html_usermanual_snippets.html'
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/deploy-ss3-docs.yml@main
